#Formato:                        El lunes es el dia 0
# Nombre:
#   - Mensaje
#   - [Hora de entrega, numero del dia de la entrega]  
groups:
  FIE - 1DB: 
    - 'Good Morning'
    - ['10:45',0]
  PFD 1DB:
    - 'Buenos días'
    - ['08:40',1]
  Ingles - Sección B:
    - 'Good Morning'
    - ['10:00',[1,3]]
  C.A.L III 1DB:
    - 'Good Morning'
    - ['08:00',2]
  FON I 1DB:
    - 'Good Morning'
    - ['10:45',2]
  VERBAL SKILL:
    - 'Good Morning'
    - ['08:00',3]
  Gramátoca Española I-1DB:
    - 'Buenos días'
    - ['10:00',4]
  Team odiosito:
    - 'A Despertarrrrrr'
    - ['08:00',[0,1,2,3,4,5,6]]
  Grupo:
    - 'Probando'
    - ['10:15',[0,1,2,3,4,5,6]]
persons:

